<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns="http://www.w3.org/1999/xhtml"
                exclude-result-prefixes="#all"
                xpath-default-namespace="http://www.w3.org/1999/xhtml"
                version="3.0">
   <xd:doc xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" scope="stylesheet">
      <xd:desc>
         <xd:p>Created on 2019-12-13 by an automated process.</xd:p>
         <xd:p>
            <xd:b>Authors:</xd:b> Joey Takeda and Martin Holmes</xd:p>
         <xd:p>This is the temporary stylesheet derived from file:/Volumes/workspace/staticSearch/config.xml and generated by file:/Volumes/workspace/staticSearch/xsl/create_config_xsl.xsl.
                            See <xd:a href="create_config_xsl.xsl">create_config_xsl.xsl</xd:a> (or https://github.com/projectEndings/staticSearch/blob/master/xsl/create_config_xsl.xsl)
                            for further information on how this document is created and the purpose it serves for the static search codebase.
                        </xd:p>
      </xd:desc>
   </xd:doc>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="configFile">file:/Volumes/workspace/staticSearch/config.xml</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="searchFile">file:/Volumes/workspace/staticSearch/test/search.html</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="recurse"
              select="true()"/>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="phrasalSearch"
              select="true()"/>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="createContexts"
              select="true()"/>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="maxContexts">3</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="totalKwicLength">15</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="kwicTruncateString">...</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="verbose"
              select="true()"/>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="stopwordsFile">file:/Volumes/workspace/staticSearch/xsl/english_stopwords.txt</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="dictionaryFile">file:/Volumes/workspace/staticSearch/xsl/english_words.txt</xsl:param>
   <xsl:param xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
              xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
              xmlns:tei="http://www.tei-c.org/ns/1.0"
              name="indentJSON"
              select="true()"/>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="collectionDir">file:/Volumes/workspace/staticSearch/test</xsl:variable>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="outDir">file:/Volumes/workspace/staticSearch/test/staticSearch</xsl:variable>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="tempDir">file:/Volumes/workspace/staticSearch/test/staticSearch/temp</xsl:variable>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="ssBaseDir">file:/Volumes/workspace/staticSearch</xsl:variable>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="docs"
                 select="collection(concat($collectionDir, '?select=*.*htm*;recurse=yes'))[not(starts-with(document-uri(.),$tempDir))]"/>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="tokenizedDocs"
                 select="collection(concat($tempDir, '?select=*_tokenized.*htm*;recurse=yes'))"/>
   <xsl:template xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="echoParams">
      <xsl:if test="$verbose">
         <xsl:message>$configFile: <xsl:value-of select="$configFile"/>
         </xsl:message>
         <xsl:message>$searchFile: <xsl:value-of select="$searchFile"/>
         </xsl:message>
         <xsl:message>$recurse: <xsl:value-of select="$recurse"/>
         </xsl:message>
         <xsl:message>$phrasalSearch: <xsl:value-of select="$phrasalSearch"/>
         </xsl:message>
         <xsl:message>$createContexts: <xsl:value-of select="$createContexts"/>
         </xsl:message>
         <xsl:message>$maxContexts: <xsl:value-of select="$maxContexts"/>
         </xsl:message>
         <xsl:message>$totalKwicLength: <xsl:value-of select="$totalKwicLength"/>
         </xsl:message>
         <xsl:message>$kwicTruncateString: <xsl:value-of select="$kwicTruncateString"/>
         </xsl:message>
         <xsl:message>$verbose: <xsl:value-of select="$verbose"/>
         </xsl:message>
         <xsl:message>$stopwordsFile: <xsl:value-of select="$stopwordsFile"/>
         </xsl:message>
         <xsl:message>$dictionaryFile: <xsl:value-of select="$dictionaryFile"/>
         </xsl:message>
         <xsl:message>$indentJSON: <xsl:value-of select="$indentJSON"/>
         </xsl:message>
         <xsl:message>$collectionDir: <xsl:value-of select="$collectionDir"/>
         </xsl:message>
         <xsl:message>$outDir: <xsl:value-of select="$outDir"/>
         </xsl:message>
         <xsl:message>$tempDir: <xsl:value-of select="$tempDir"/>
         </xsl:message>
      </xsl:if>
   </xsl:template>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="stopwordsFileXml"
                 select="doc('file:/Volumes/workspace/staticSearch/test/staticSearch/dicts/english_stopwords.xml')"/>
   <xsl:variable xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 name="dictionaryFileXml"
                 select="doc('file:/Volumes/workspace/staticSearch/test/staticSearch/dicts/english_words.xml')"/>
   <xsl:key xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
            xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
            xmlns:tei="http://www.tei-c.org/ns/1.0"
            name="w"
            match="hcmc:word"
            use="."/>
   <xsl:template xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 match="*[matches(@class,'(^|\s)toponym(\s|$)')] | *[@class='ed_note']"
                 priority="1"
                 mode="clean">
      <xsl:if test="$verbose">
         <xsl:message>Template #clean: retaining <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*|node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
   <xsl:template xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 match="abbr[parent::span/span[@class='expan']]"
                 priority="1"
                 mode="clean">
      <xsl:if test="$verbose">
         <xsl:message>Template #clean: Deleting <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
   </xsl:template>
   <xsl:template xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 match="*[@class='ed_note'] | div[@class='not_context']"
                 priority="1"
                 mode="contextualize">
      <xsl:if test="$verbose">
         <xsl:message>Template #contextualize: Adding @data-staticSearch-context flag to <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*" mode="#current"/>
         <xsl:if test="self::*[@class='ed_note']">
            <xsl:attribute name="data-staticSearch-context" select="'true'"/>
         </xsl:if>
         <xsl:if test="self::div[@class='not_context']">
            <xsl:attribute name="data-staticSearch-context" select="'false'"/>
         </xsl:if>
         <xsl:apply-templates select="node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
   <xsl:template xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                 xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                 xmlns:tei="http://www.tei-c.org/ns/1.0"
                 match="*[matches(@class,'(^|\s)toponym(\s|$)')]"
                 priority="1"
                 mode="weigh">
      <xsl:if test="$verbose">
         <xsl:message>Template #weigh: Adding @data-weight to <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*" mode="#current"/>
         <xsl:if test="self::*[matches(@class,'(^|\s)toponym(\s|$)')]">
            <xsl:attribute name="data-staticSearch-weight" select="2"/>
         </xsl:if>
         <xsl:apply-templates select="node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
</xsl:stylesheet>
